/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AVL: typeof import('./src/components/AVL.vue')['default']
    BT: typeof import('./src/components/BT.vue')['default']
    CPM: typeof import('./src/components/CPM.vue')['default']
    Dijkstra: typeof import('./src/components/Dijkstra.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Floyd: typeof import('./src/components/Floyd.vue')['default']
    Hash: typeof import('./src/components/Hash.vue')['default']
    HeapSort: typeof import('./src/components/HeapSort.vue')['default']
    HuffmanTree: typeof import('./src/components/HuffmanTree.vue')['default']
    MergeSort: typeof import('./src/components/MergeSort.vue')['default']
    MST: typeof import('./src/components/MST.vue')['default']
    Prim: typeof import('./src/components/Prim.vue')['default']
    QuickSort: typeof import('./src/components/QuickSort.vue')['default']
    RadixSort: typeof import('./src/components/RadixSort.vue')['default']
    Readme: typeof import('./src/components/Readme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellSort: typeof import('./src/components/ShellSort.vue')['default']
    TopologicalSort: typeof import('./src/components/TopologicalSort.vue')['default']
  }
}
